/* ============================================================
   RESERVATIONER TIL ARRANGEMENTER  (30/8-2026)
   ------------------------------------------------------------
   Kundens ord: "kalender og arrangementer er fedt og godt, men
   hvor kommer reservationerne hen, hvad kan admin styre, hvordan
   gør vi det bulletproof ift kunder og admin."

   Svaret på det første er: ingen steder. Knappen "Reservér plads"
   på h-kalender.html har siddet der siden designet kom 23/8, og
   den har aldrig sendt noget — der er ingen tabel bag den. Det
   stod som et kendt hul i CLAUDE.md ("kalenderens Reservér plads
   med pladstælling findes ikke i databasen endnu"). Den her fil
   lukker det.

   KØR EFTER kalender.sql. Filen bruger is_admin_for() fra
   flerlejer.sql og tabellen kalender.

   ------------------------------------------------------------
   ⚠️ HVORFOR EN TABEL OG IKKE ET FELT PÅ KALENDEREN
   ------------------------------------------------------------
   En reservation er navn, nummer og et antal — ét menneske pr.
   række. Talte vi bare op i en kolonne på arrangementet, ville
   personalet have et TAL og ingen liste: ingen at krydse af ved
   døren, ingen at ringe til, hvis koncerten aflyses, og ingen
   måde at fortryde en enkelt på. Det er samme skelet som resten
   af huset: gæsten skriver, personalet ser, status går én vej.

   ------------------------------------------------------------
   ⚠️ PLADSERNE TÆLLES I DATABASEN, IKKE I BROWSEREN
   ------------------------------------------------------------
   To gæster, der trykker samtidig på den sidste plads, er ikke et
   sjældent tilfælde til en koncert — det er DET, der sker, når
   linket lige er delt. Browseren kan ikke vide, hvad den anden
   gør. Bremsen herunder tæller inde i transaktionen og siger nej
   til nummer to.

   Og den tæller kun det, der IKKE er afvist: et afslag skal
   frigive pladsen igen, ellers står en aflyst reservation og
   spærrer for en, der gerne vil.
   ============================================================ */

begin;

-- ------------------------------------------------------------
-- 1) ARRANGEMENTET SKAL KUNNE TAGE IMOD
--    ------------------------------------------------------------
--    ⚠️ TILMELDING ER SLÅET FRA SOM STANDARD. De fleste
--    arrangementer på en havn er "kig forbi" — musik på molen,
--    hvor man ikke booker. Stod tilmeldingen til som standard,
--    ville hvert eneste arrangement, ejeren opretter, pludselig
--    bede gæsterne om navn og nummer, og han ville ikke vide
--    hvorfor. Han slår den til, når der ER pladser at fordele.
-- ------------------------------------------------------------
alter table public.kalender
  add column if not exists tilmelding boolean not null default false;

/* Tomt loft = ingen grænse. Et arrangement kan have tilmelding
   uden et tal ("sig til, så vi ved hvor mange stole") — og et
   loft på nul ville betyde udsolgt fra første sekund. */
alter table public.kalender
  add column if not exists pladser int;

alter table public.kalender
  drop constraint if exists kalender_pladser_ok;
alter table public.kalender
  add constraint kalender_pladser_ok
  check (pladser is null or pladser between 1 and 2000);

/* Prisen er ejerens ord, ikke et tal vi regner på: den står som
   fritekst ("gratis", "50,- ved indgangen", "inkl. en øl"), fordi
   der ikke er betaling i systemet, og en kolonne med kroner ville
   se ud, som om der var. */
alter table public.kalender
  add column if not exists pris_tekst text;

alter table public.kalender
  drop constraint if exists kalender_pris_tekst_ok;
alter table public.kalender
  add constraint kalender_pris_tekst_ok
  check (pris_tekst is null or char_length(pris_tekst) <= 120);

/* Klokkeslæt på et arrangement. kalender.lukker_kl er tidlig
   lukning og noget helt andet — de to må ikke blandes sammen. */
alter table public.kalender
  add column if not exists start_kl time;

-- ------------------------------------------------------------
-- 2) TABELLEN
-- ------------------------------------------------------------
create table if not exists public.reservationer (
  id             bigint generated by default as identity primary key,
  lokation_id    text not null default 'mosede'
                 references public.lokationer(id) on delete cascade,

  /* ⚠️ HÅRD NØGLE TIL ARRANGEMENTET. Slettes rækken i kalenderen,
     skal reservationerne følge med — en tilmelding til noget, der
     ikke findes, kan ingen gøre noget ved, og den ville stå og
     tælle plads på et arrangement, der er væk. */
  kalender_id    bigint not null
                 references public.kalender(id) on delete cascade,

  reference      text not null unique,
  navn           text not null,
  telefon        text not null,
  email          text,
  antal_personer int not null default 1,
  besked         text,

  status         text not null default 'ny',
  intern_note    text,
  slettet        timestamptz,

  oprettet       timestamptz not null default now(),
  aendret        timestamptz not null default now(),

  constraint reservation_navn_ok
    check (char_length(btrim(navn)) between 2 and 80),
  constraint reservation_telefon_ok
    check (char_length(regexp_replace(telefon, '[^0-9]', '', 'g')) between 8 and 15),
  constraint reservation_email_ok
    check (email is null or email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[a-zA-Z]{2,}$'),
  /* Et selskab på tredive til en koncert er en aftale, ikke en
     tilmelding — så ringer man. */
  constraint reservation_antal_ok
    check (antal_personer between 1 and 20),
  constraint reservation_besked_ok
    check (besked is null or char_length(besked) <= 1000),
  /* Samme ord som bordene: kommet, sagt ja, sagt nej, udeblevet.
     Ordene er tabellens egne og oversættes ét sted i admin. */
  constraint reservation_status_ok
    check (status in ('ny', 'bekraeftet', 'afvist', 'udeblevet'))
);

/* ⚠️ DUBLETVAGT: samme nummer, samme arrangement. Trykker gæsten
   to gange, fordi siden var langsom, må der ikke stå to. Den
   tæller ikke de slettede eller de afviste — har personalet sagt
   nej, skal hun kunne prøve igen. */
create unique index if not exists reservation_dublet
  on public.reservationer (kalender_id, telefon)
  where slettet is null and status <> 'afvist';

create index if not exists reservation_pr_arrangement
  on public.reservationer (lokation_id, kalender_id, status);

-- ------------------------------------------------------------
-- 3) ADGANGEN
--    ------------------------------------------------------------
--    Samme regel som bestillinger, borde og forespørgsler, af
--    samme grund: en række er navn og telefonnummer på et
--    menneske. Måtte anon læse her, kunne enhver hente hele
--    gæstelisten til fredagens koncert med én linje i en
--    browserkonsol.
--
--    HVAD GÆSTEN IKKE MÅ SÆTTE: status skal være 'ny', og den
--    interne note skal være tom.
-- ------------------------------------------------------------
alter table public.reservationer enable row level security;

drop policy if exists reservationer_opret_gaest on public.reservationer;
create policy reservationer_opret_gaest on public.reservationer
  for insert to anon, authenticated
  with check (status = 'ny' and intern_note is null and slettet is null);

drop policy if exists reservationer_laes_admin on public.reservationer;
create policy reservationer_laes_admin on public.reservationer
  for select using (public.is_admin_for(lokation_id));

drop policy if exists reservationer_ret_admin on public.reservationer;
create policy reservationer_ret_admin on public.reservationer
  for update using (public.is_admin_for(lokation_id))
  with check (public.is_admin_for(lokation_id));

drop policy if exists reservationer_slet_admin on public.reservationer;
create policy reservationer_slet_admin on public.reservationer
  for delete using (public.is_admin_for(lokation_id));

commit;

begin;

-- ------------------------------------------------------------
-- 4) BREMSEN — OG PLADSTÆLLINGEN
--    ------------------------------------------------------------
--    ⚠️ security definer ER HELE FORUDSÆTNINGEN. Gæsten er anon
--    og må ikke læse tabellen; uden det ville tællingerne give
--    nul, og bremsen ville se ud til at virke uden at gøre noget.
--    Præcis den fejl, lukkedag-værnet faldt i 23/8.
--
--    Fejlnavnene står i teksten med vilje: js/store.js kender dem
--    og oversætter dem til noget, gæsten kan handle på. Retter du
--    et navn her, skal det rettes dér.
-- ------------------------------------------------------------
create or replace function public.reservation_bremse()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  arr        public.kalender%rowtype;
  optaget    int;
  fra_nummer int;
  paa_stedet int;
begin
  select * into arr from public.kalender k where k.id = new.kalender_id;

  /* Findes arrangementet ikke, eller er det ikke offentligt, er
     der ikke noget at melde sig til. Et internt arrangement er
     personalets egen note — "Bent har ferie" — og en tilmelding
     til DEN ville være en fremmed, der har gættet et id. */
  if arr.id is null or not arr.offentlig then
    raise exception 'reservation_findes_ikke';
  end if;

  if not arr.tilmelding then
    raise exception 'reservation_lukket';
  end if;

  /* Overstået. Datoen er arrangementets, ikke dagens: en koncert
     i går kan ingen melde sig til, og en formular, der er åben i
     en gammel fane, må ikke kunne. */
  if coalesce(arr.slut_dato, arr.dato) < current_date then
    raise exception 'reservation_overstaaet';
  end if;

  /* ⚠️ PLADSERNE TÆLLES HER, IKKE I BROWSEREN. To gæster på den
     sidste plads samtidig er ikke et sjældent tilfælde — det er
     dét, der sker, når linket lige er delt.

     Kun det, der ikke er afvist eller slettet, tæller: et afslag
     skal frigive pladsen igen, ellers spærrer en aflyst
     reservation for en, der gerne vil. Udeblevne tæller MED —
     de har stadig en plads, indtil nogen siger andet. */
  if arr.pladser is not null then
    select coalesce(sum(r.antal_personer), 0) into optaget
      from public.reservationer r
     where r.kalender_id = new.kalender_id
       and r.slettet is null
       and r.status <> 'afvist';

    if optaget + new.antal_personer > arr.pladser then
      raise exception 'reservation_udsolgt';
    end if;
  end if;

  /* Hvad en browser kan gøre én gang, kan et script gøre ti
     tusind gange. */
  select count(*) into fra_nummer
    from public.reservationer r
   where r.telefon = new.telefon
     and r.oprettet > now() - interval '24 hours';
  if fra_nummer >= 5 then
    raise exception 'reservation_bremse_nummer';
  end if;

  select count(*) into paa_stedet
    from public.reservationer r
   where r.lokation_id = new.lokation_id
     and r.oprettet > now() - interval '1 hour';
  if paa_stedet >= 60 then
    raise exception 'reservation_bremse_travlt';
  end if;

  return new;
end $$;

/* ⚠️ KUN VED INSERT. Personalet skal kunne bekræfte og afvise
   hele dagen uden at støde ind i en bremse, der er bygget mod
   noget helt andet — og skal kunne sige ja til nummer 41 til et
   arrangement med 40 pladser, hvis de selv finder en stol. */
drop trigger if exists reservation_bremse on public.reservationer;
create trigger reservation_bremse
  before insert on public.reservationer
  for each row execute function public.reservation_bremse();

-- ------------------------------------------------------------
-- 5) HVOR MANGE PLADSER ER DER TILBAGE?
--    ------------------------------------------------------------
--    ⚠️ VISNINGEN MÅ ALDRIG FÅ EN KOLONNE MERE. Samme regel som
--    optagne_dage og bord_travlhed: den kører med sin EJERS øjne
--    og springer adgangsreglerne over — det er hele meningen, for
--    gæsten skal kunne se "3 pladser tilbage" uden at kunne læse,
--    HVEM der har taget de andre.
--
--    Kommer der et navn, et nummer eller en mail med, er
--    gæstelisten åben for internettet, og siden ville se helt
--    rigtig ud imens. Prøve 8 tæller kolonnerne.
-- ------------------------------------------------------------
drop view if exists public.arrangement_pladser;
create view public.arrangement_pladser
with (security_invoker = false) as
  select k.id            as kalender_id,
         k.lokation_id,
         k.pladser,
         coalesce(sum(r.antal_personer) filter (
           where r.slettet is null and r.status <> 'afvist'), 0)::int as optaget
    from public.kalender k
    left join public.reservationer r on r.kalender_id = k.id
   where k.type = 'arrangement'
     and k.offentlig
     and k.tilmelding
   group by k.id, k.lokation_id, k.pladser;

grant select on public.arrangement_pladser to anon, authenticated;

commit;

/* Supabases SQL Editor viser kun den SIDSTE sætnings svar — se
   README. Derfor en select til sidst i stedet for en notice. */
select
  case
    when (select count(*) from pg_policies
           where schemaname = 'public' and tablename = 'reservationer') = 4
     and (select count(*) from pg_trigger
           where tgname = 'reservation_bremse') = 1
     and (select count(*) from information_schema.columns
           where table_schema = 'public' and table_name = 'kalender'
             and column_name in ('tilmelding', 'pladser', 'pris_tekst', 'start_kl')) = 4
     and to_regclass('public.arrangement_pladser') is not null
      then '✅ KLAR — arrangementer kan tage imod reservationer'
    else '❌ NOGET MANGLER — se linjerne ovenfor'
  end as resultat;
