-- ============================================================
--  BORDENE OG DERES QR-KODER  (august 2026)
--  ------------------------------------------------------------
--  Kør i Mosede-projektet: epwyjzakvvbxtpvnhvbn
--  Tjek projekt-id'et i adresselinjen, FØR du trykker Run.
--
--  Kør EFTER: setup.sql → flerlejer.sql → bremse.sql →
--  spis-her.sql. Filen bygger oven på kolonnen hvordan.
--
--  HVAD DEN GØR
--  ------------------------------------------------------------
--  Gæsten sidder ved bord 7 og scanner mærkatet på bordet. Hun
--  får hele lugens kort på sin egen telefon, bestiller, og
--  bestillingen lander i admin med BORDET på — ikke et
--  afhentningstidspunkt, personalet skal gætte sig til.
--
--  To ting kommer til:
--
--    1) Tabellen `borde` — hvilke borde der findes. Numrene må
--       IKKE stå i koden. Ejeren flytter om på trædækket, og en
--       ommøblering må ikke være en kodeændring hos os. Derfor
--       oprettes bordene i admin, og skiltene tegnes ud fra
--       listen.
--
--    2) Kolonnen `bord_nummer` på bestillinger, og et værn om
--       den.
--
--  VÆRNET, OG HVAD DET IKKE ER
--  ------------------------------------------------------------
--  Et bord skal FINDES, før man kan bestille til det. Uden det
--  kunne en hvilken som helst adresse med ?bord=hvadsomhelst
--  sende en bestilling ind, og køkkenet ville stå med mad til et
--  bord, der ikke er der.
--
--  Det er ikke et værn mod en, der scanner bord 4 fra
--  parkeringspladsen og bestiller ti fadøl. Det kræver, at
--  personalet ÅBNER bordet, og det er en beslutning, ejeren skal
--  træffe — se listen "Ejeren skal bekræfte" i README. Indtil da
--  står bestillingen i admin med bordet på, og personalet ser
--  den, før maden laves.
--
--  Og et bord kan kun bestilles til SPIS HER. En bestilling, der
--  både er til bord 7 og skal hentes ved lugen, er to ting på én
--  gang, og køkkenet kan ikke gøre begge.
--
--  Filen kan køres igen: create if not exists, create or replace
--  og drop/create på reglerne.
-- ============================================================

-- ------------------------------------------------------------
-- 1) BORDENE
-- ------------------------------------------------------------
create table if not exists public.borde (
  id           bigint generated by default as identity primary key,
  lokation_id  text not null default 'mosede' references public.lokationer(id),

  /* TEKST OG IKKE ET TAL. Bordene på et trædæk hedder ikke altid
     1, 2, 3 — der er "Terrassen 2" og "Ved gavlen". Et heltal
     ville tvinge ejeren til at give dem numre, han ikke bruger,
     og så ville skiltet og virkeligheden sige hver sit. */
  nummer       text not null,

  -- Valgfrit. Vi ved ikke, hvor mange der kan sidde ved hvert
  -- bord, og et gæt her bliver til et løfte i en bordbestilling.
  pladser      int,

  placering    text not null default 'inde',
  aktiv        boolean not null default true,
  sortering    int not null default 0,

  oprettet     timestamptz not null default now(),
  aendret      timestamptz not null default now(),

  constraint bord_nummer_ok
    check (char_length(btrim(nummer)) between 1 and 40),
  constraint bord_pladser_ok
    check (pladser is null or pladser between 1 and 50),
  constraint bord_placering_ok
    check (placering in ('inde', 'ude'))
);

comment on table public.borde is
  'De fysiske borde. Numrene bor her og ikke i koden — en ommøblering på trædækket må ikke være en kodeændring.';

/* To borde med samme nummer er en dobbeltbooking, der venter på
   at ske: to mærkater peger samme sted hen, og maden går til det
   forkerte selskab. lower(btrim()) fordi "Bord 7" og "bord 7 " er
   det samme bord for alle andre end en database. */
create unique index if not exists borde_nummer_unikt
  on public.borde (lokation_id, lower(btrim(nummer)));

create index if not exists borde_raekkefoelge_idx
  on public.borde (lokation_id, sortering, id);

-- ------------------------------------------------------------
-- 2) ADGANGEN
--    ------------------------------------------------------------
--    Bordene er det ENESTE her, alle må læse. Gæstens telefon
--    skal kunne slå op, om bord 7 findes, før hun får en formular
--    — og skiltene tegnes af den samme liste. Der står ingen
--    personoplysninger i tabellen: et bordnummer og et antal
--    pladser er ikke nogens.
--
--    Skrive må kun personalet.
-- ------------------------------------------------------------
alter table public.borde enable row level security;

drop policy if exists borde_laes_alle on public.borde;
create policy borde_laes_alle on public.borde
  for select using (true);

drop policy if exists borde_opret_admin on public.borde;
create policy borde_opret_admin on public.borde
  for insert to authenticated
  with check (public.is_admin_for(lokation_id));

drop policy if exists borde_ret_admin on public.borde;
create policy borde_ret_admin on public.borde
  for update using (public.is_admin_for(lokation_id))
  with check (public.is_admin_for(lokation_id));

drop policy if exists borde_slet_admin on public.borde;
create policy borde_slet_admin on public.borde
  for delete using (public.is_admin_for(lokation_id));

/* RETTIGHEDERNE SKREVET UD, og det er den eneste fil i mappen,
   der gør det. Supabase giver selv anon og authenticated adgang
   til nye tabeller i public, så resten af filerne kan nøjes med
   adgangsreglerne. Men `borde` er den FØRSTE tabel, en gæst skal
   kunne LÆSE — alle de andre må hun kun skrive i. Mangler
   rettigheden (en anden opsætning, en kopi af projektet), fejler
   det ikke højt: bordlisten er bare tom, telefonen siger "vi
   kender ikke bord 7", og ingen kan se hvorfor.

   Row level security bestemmer stadig rækkerne. Det her er kun
   døren ind til tabellen. */
grant select on public.borde to anon, authenticated;
grant insert, update, delete on public.borde to authenticated;

-- ------------------------------------------------------------
-- 3) BORDET PÅ BESTILLINGEN
-- ------------------------------------------------------------
alter table public.bestillinger
  add column if not exists bord_nummer text;

comment on column public.bestillinger.bord_nummer is
  'Bordet, der er bestilt fra med QR-koden. Tom ved alt andet.';

alter table public.bestillinger
  drop constraint if exists bestilling_bord_nummer_ok;

alter table public.bestillinger
  add constraint bestilling_bord_nummer_ok
  check (bord_nummer is null
         or char_length(btrim(bord_nummer)) between 1 and 40);

/* BEGGE VEJE, som ved leveringsadressen. Et bordnummer på en
   afhentning er en bestilling, køkkenet ikke kan udføre: skal
   maden ud på bord 7, eller ligge klar i lugen? Og et spis
   her-bord uden nummer er bare spis her — det er stadig i
   orden, for man kan gå ind og bestille ved lugen og sætte sig. */
alter table public.bestillinger
  drop constraint if exists bestilling_bord_hvordan_ok;

alter table public.bestillinger
  add constraint bestilling_bord_hvordan_ok
  check (bord_nummer is null or hvordan = 'spis_her');

-- Personalet spørger "hvad har bord 7 bestilt i dag".
create index if not exists bestillinger_bord_idx
  on public.bestillinger (lokation_id, bord_nummer, hent_dato)
  where bord_nummer is not null;

-- ------------------------------------------------------------
-- 4) VÆRNET: BORDET SKAL FINDES
--    ------------------------------------------------------------
--    security definer af samme grund som lukkedagsværnet — men
--    fejlen vender modsat, og det er værd at have set.
--
--    Værnet spørger "findes bordet IKKE?". Slår det op med
--    GÆSTENS øjne, og bliver læsereglen ovenfor en dag strammet
--    ("kun personalet skal se bordlisten" lyder fornuftigt), så
--    finder det ingen borde — og afviser hver eneste bestilling
--    fra hvert eneste bord. Ikke et hul, men en luge, der siger
--    "vi kender ikke bord 7" til alle, mens bordet står lige der
--    med et trykt skilt på.
--
--    Lukkedagsværnet fejler den anden vej og lukker alt IND.
--    Begge dele er lige stille, og begge dele bor i, at en
--    udløser kan se noget andet end den, der skrev den. Prøve 14
--    i proev-bordkort.sql står vagt om det her.
--
--    Fejlnavnet står i teksten med vilje: js/store.js kender det
--    og oversætter det til dansk. Retter du navnet her, skal det
--    rettes dér.
-- ------------------------------------------------------------
create or replace function public.mosede_bord_findes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.bord_nummer is null then
    return new;
  end if;

  if not exists (
    select 1 from public.borde b
     where b.lokation_id = new.lokation_id
       and b.aktiv
       and lower(btrim(b.nummer)) = lower(btrim(new.bord_nummer))
  ) then
    raise exception 'bestilling_ukendt_bord';
  end if;

  return new;
end $$;

drop trigger if exists bestilling_bord_findes on public.bestillinger;
create trigger bestilling_bord_findes
  before insert on public.bestillinger
  for each row execute function public.mosede_bord_findes();

-- Rapport. Supabases SQL Editor viser kun den sidste sætnings
-- svar — se README-afsnittet "Supabases SQL Editor viser ikke
-- beskeder".
select
  case when (
    select count(*) from information_schema.triggers
     where trigger_name = 'bestilling_bord_findes'
  ) >= 1 and (select to_regclass('public.borde') is not null)
    then '✅ BORDENE ER PÅ PLADS — opret dem i admin under Borde, og kør supabase/proev-bordkort.sql'
    else '❌ NOGET MANGLER — læs fejlbeskeden ovenfor og kør filen igen'
  end as svar;
