-- ============================================================
--  BORDBESTILLINGER  (fase 4)
--  ------------------------------------------------------------
--  Kør EFTER flerlejer.sql — filen bruger is_admin_for() derfra.
--  Rækkefølgen er altså:
--    setup.sql → flerlejer.sql → bremse.sql → menukort.sql
--    → forespoergsler.sql → kalender.sql → borde.sql
--
--  Kan køres igen uden at ødelægge noget.
--
--  ------------------------------------------------------------
--  GÆSTEN SPØRGER, PERSONALET BEKRÆFTER
--  ------------------------------------------------------------
--  En række her er et ØNSKE om et bord, ikke et bord. Ja'et gives
--  kun ét sted: i admin, hvor personalet ser hele dagens billede
--  — hvor mange pladser der allerede er sagt ja til, målt mod
--  antallet af pladser, som sættes i indstillinger. Derfor kan to
--  gæster ikke få ja til det samme bord: der er kun én, der siger
--  ja, og hun kan se, hvad hun har sagt ja til.
--
--  Databasen håndhæver med vilje IKKE en kapacitet. Antallet af
--  pladser er personalets arbejdsredskab og kan ændres når som
--  helst i admin — en hård grænse her ville afvise gæstens ØNSKE
--  på tal, der var rigtige i går. Et ønske koster ingenting at
--  tage imod, og personalet svarer alligevel på hvert eneste.
--
--  Kalenderen er fundamentet på gæstesiden: lukkedage kan ikke
--  vælges, og tidlige lukninger skærer tiderne til. Databasen
--  behøver derfor kun at afvise det åbenlyse vrøvl.
--
--  ------------------------------------------------------------
--  KØRER DU DEN PÅ EN BAR POSTGRES?
--  ------------------------------------------------------------
--  Supabase giver selv anon og authenticated adgang til nye
--  tabeller. Gør du det ikke, kan gæsten ikke sende noget. Kør:
--
--    grant all on all tables in schema public to anon, authenticated;
--    grant usage, select on all sequences in schema public
--      to anon, authenticated;
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1) TABELLEN
-- ------------------------------------------------------------
/* id er en IDENTITY-kolonne og ikke bigserial — samme fælde som
   ved bestillingerne: med bigserial mangler anon usage på
   sekvensen, og fejlen ligner et hul i adgangsreglerne uden at
   være det. */
create table if not exists public.bordbestillinger (
  id            bigint generated by default as identity primary key,

  -- Koden gæsten får at vide. Laves i browseren, fordi gæsten
  -- ikke må kunne læse tabellen bagefter. BO, hvor bestillinger
  -- har SM og forespørgsler FO.
  reference     text not null unique,

  lokation_id   text not null default 'mosede' references public.lokationer(id) on delete cascade,

  navn          text not null,
  telefon       text not null,
  email         text,

  /* Dato, tid og antal er PÅKRÆVEDE, hvor forespørgslerne har dem
     frivillige. Det er ikke inkonsekvens: "vi holder fest engang
     til foråret" er et rigtigt spørgsmål, men "vi vil gerne have
     et bord engang" er ikke noget, personalet kan svare på. Et
     bord ER en dato, et klokkeslæt og et antal stole. */
  dato          date not null,
  tid           time not null,
  antal_personer int not null,

  besked        text,

  status        text not null default 'ny',
  -- Personalets egen note. Adgangsreglen kræver, at den er tom
  -- ved oprettelse — gæsten må ikke skrive i personalets felt.
  intern_note   text,

  oprettet      timestamptz not null default now(),
  aendret       timestamptz not null default now(),

  /* Lag 3 af valideringen. Formularen tjekker det samme, og
     js/store.js tjekker det igen — men en formular kan omgås med
     to linjer i konsollen, og databasen kan ikke. */
  constraint bord_navn_ok
    check (char_length(btrim(navn)) between 2 and 80),

  constraint bord_telefon_ok
    check (char_length(regexp_replace(telefon, '[^0-9]', '', 'g')) between 8 and 15),

  constraint bord_email_ok
    check (email is null or email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[a-zA-Z]{2,}$'),

  /* 120 dage som bestillingerne — et bord bookes ikke to år frem.
     Det ene døgn bagud dækker, at Danmark er en time foran UTC. */
  constraint bord_dato_ok
    check (dato between current_date - 1 and current_date + 120),

  /* 100 og ikke 500: hundrede mennesker er ikke et bord, det er
     et selskab, og dét har sin egen indgang med sin egen samtale. */
  constraint bord_antal_ok
    check (antal_personer between 1 and 100),

  constraint bord_besked_ok
    check (besked is null or char_length(besked) <= 500),

  constraint bord_status_ok
    check (status in ('ny', 'bekraeftet', 'afvist')),

  -- Dobbelttryk. Samme telefon, samme dag, samme tid er ét ønske
  -- – ikke to. Fanger gæsten, der trykker "Send" to gange, fordi
  -- der ikke skete noget med det samme.
  constraint bord_ikke_dobbelt
    unique (telefon, dato, tid)
);

comment on table public.bordbestillinger is
  'Ønsker om et bord. Gæsten må skrive, kun personalet må læse — og kun personalet siger ja.';

-- Personalet åbner fanen og vil se de nye først — og dagens
-- billede samles pr. dato, når der skal siges ja.
create index if not exists bordbestillinger_status_idx
  on public.bordbestillinger (status, oprettet desc);

create index if not exists bordbestillinger_dato_idx
  on public.bordbestillinger (lokation_id, dato, tid);

-- Én pr. tælling i bremsen nedenfor.
create index if not exists bordbestillinger_bremse_nummer_idx
  on public.bordbestillinger (telefon, oprettet desc);

create index if not exists bordbestillinger_bremse_sted_idx
  on public.bordbestillinger (lokation_id, oprettet desc);


-- ------------------------------------------------------------
-- 2) ADGANGEN: GÆSTEN MÅ SKRIVE, MEN IKKE LÆSE
--    ------------------------------------------------------------
--    Samme regel som bestillinger og forespørgsler, af samme
--    grund: en række er navn og telefonnummer på et menneske, der
--    har fortalt, hvornår de IKKE er hjemme. Måtte anon læse her,
--    kunne enhver hente listen med én linje i en browserkonsol.
--
--    HVAD GÆSTEN IKKE MÅ SÆTTE: status skal være 'ny', og den
--    interne note skal være tom — ellers kunne man indsætte et
--    ønske, der ser bekræftet ud, eller skrive i personalets felt.
-- ------------------------------------------------------------
alter table public.bordbestillinger enable row level security;

drop policy if exists bordbestillinger_opret_gaest on public.bordbestillinger;
create policy bordbestillinger_opret_gaest on public.bordbestillinger
  for insert to anon, authenticated
  with check (status = 'ny' and intern_note is null);

drop policy if exists bordbestillinger_laes_admin on public.bordbestillinger;
create policy bordbestillinger_laes_admin on public.bordbestillinger
  for select using (public.is_admin_for(lokation_id));

drop policy if exists bordbestillinger_ret_admin on public.bordbestillinger;
create policy bordbestillinger_ret_admin on public.bordbestillinger
  for update using (public.is_admin_for(lokation_id))
  with check (public.is_admin_for(lokation_id));

drop policy if exists bordbestillinger_slet_admin on public.bordbestillinger;
create policy bordbestillinger_slet_admin on public.bordbestillinger
  for delete using (public.is_admin_for(lokation_id));


-- ------------------------------------------------------------
-- 3) BREMSEN
--    ------------------------------------------------------------
--    Hvad en browser kan gøre én gang, kan et script gøre ti
--    tusind gange. Dobbelttrykket fanges af den unikke nøgle
--    ovenfor (dato og tid er påkrævede her, så nøglen virker —
--    forespørgslerne måtte bruge et tidsvindue, fordi deres dato
--    kan være NULL). Bremsen tager resten:
--
--    security definer er HELE forudsætningen. Gæsten er anon og
--    må ikke læse tabellen — uden det ville tællingerne give nul,
--    og bremsen ville se ud til at virke uden at gøre noget.
--
--    Fejlnavnene står i teksten med vilje: js/store.js kender dem
--    og oversætter dem. Retter du et navn her, skal det rettes dér.
-- ------------------------------------------------------------
create or replace function public.bord_bremse()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  fra_nummeret int;
  paa_stedet   int;
begin
  /* 3 pr. nummer i døgnet. En familie booker ét bord, måske to —
     ikke fem. Rammer et rigtigt menneske grænsen, siger
     js/store.js: ring, så tager vi den i telefonen. */
  select count(*) into fra_nummeret
    from public.bordbestillinger b
   where b.telefon = new.telefon
     and b.oprettet > now() - interval '24 hours';

  if fra_nummeret >= 3 then
    raise exception 'bord_bremse_nummer';
  end if;

  select count(*) into paa_stedet
    from public.bordbestillinger b
   where b.lokation_id = new.lokation_id
     and b.oprettet > now() - interval '1 hour';

  if paa_stedet >= 20 then
    raise exception 'bord_bremse_travlt';
  end if;

  return new;
end $$;

/* Kun ved insert. Personalet skal kunne bekræfte hele dagen uden
   at støde ind i en bremse, der er bygget mod noget helt andet. */
drop trigger if exists bord_bremse on public.bordbestillinger;
create trigger bord_bremse
  before insert on public.bordbestillinger
  for each row execute function public.bord_bremse();

commit;

-- ------------------------------------------------------------
--  ER DEN LANDET?
--  ------------------------------------------------------------
--  Supabases SQL Editor viser kun den SIDSTE sætnings svar. Står
--  der ikke fire regler og én udløser, er noget gået galt.
-- ------------------------------------------------------------
select
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'bordbestillinger') as "adgangsregler (skal være 4)",
  (select count(*) from pg_trigger
    where tgrelid = 'public.bordbestillinger'::regclass and not tgisinternal) as "bremser (skal være 1)",
  (select count(*) from public.bordbestillinger) as "bordønsker i tabellen";

-- ------------------------------------------------------------
--  BAGEFTER
--  ------------------------------------------------------------
--  Kør supabase/proev-borde.sql. Den prøver at læse på tværs af
--  to forretninger og ruller sig selv tilbage. Består den ikke,
--  kan én kunde se en andens gæster.
-- ------------------------------------------------------------
