-- ============================================================
--  DAGENS RET FÅR EN TABEL  (august 2026)
--  ------------------------------------------------------------
--  Kør i Mosede-projektet: epwyjzakvvbxtpvnhvbn
--  Tjek projekt-id'et i adresselinjen, FØR du trykker Run.
--
--  Kør EFTER setup.sql, flerlejer.sql og bremse.sql.
--  Filen kan køres igen uden at ødelægge noget.
--
--  HVORFOR
--  ------------------------------------------------------------
--  Dagens ret var ÉN indstilling: et navn, en beskrivelse og en
--  pris. Det gav tre begrænsninger, som alle tre kostede noget:
--
--  1) KUN I DAG. Menukortets ugeplan stod halvt tom — "Følger
--     snart…" fra tirsdag og frem — fordi der ikke fandtes et
--     sted at skrive torsdagens ret. Køkkenet planlægger ugen om
--     mandagen; siden kunne kun vise dagen.
--  2) KUN ÉN RET. Er der to at vælge imellem, blev de til ét
--     langt navn i det samme felt, med én pris.
--  3) INGEN UDSOLGT. Retten blev ved med at kunne bestilles, til
--     nogen huskede at tømme feltet.
--
--  ANTAL TILBAGE TÆLLES AF DATABASEN, IKKE AF ET MENNESKE
--  ------------------------------------------------------------
--  Det stod indtil nu som "IKKE bygget, og det er ikke en
--  forglemmelse": et tal, personalet tæller ned i hånden, bliver
--  forkert i løbet af en frokost, og gæst nummer syv får mad, der
--  ikke findes.
--
--  Den indvending gælder stadig — og det er præcis derfor,
--  tællingen ligger HER og ikke i browseren. En bremse trækker
--  fra, når bestillingen oprettes, og sætter udsolgt ved nul.
--  Ingen skal huske noget, og to gæster, der trykker samtidig,
--  kan ikke begge få den sidste portion: rækken låses.
--
--  Feltet er FRIVILLIGT. Er antal_tilbage tomt, tælles der ikke,
--  og retten kan bestilles, til nogen siger stop. Det er stadig
--  det rigtige for en ret, køkkenet laver i det uendelige.
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1) TABELLEN
-- ------------------------------------------------------------
create table if not exists public.dagens_retter (
  id           bigint generated by default as identity primary key,
  lokation_id  text not null default 'mosede'
               references public.lokationer(id) on delete cascade,

  dato         date not null,

  navn         text not null,
  beskrivelse  text,

  /* Prisen er frivillig — som på menukortet. En ret uden pris kan
     ses, men ikke bestilles: gæsten skal kunne se, hvad der er i
     dag, også før tallet er sat. Se Butik.dagensRetter. */
  pris         numeric(8,2),

  /* Tomt = der tælles ikke. Se noten øverst: tællingen er
     databasens, og feltet er til den ret, der laves i et bestemt
     antal portioner. */
  antal_tilbage int,

  udsolgt      boolean not null default false,
  aktiv        boolean not null default true,

  /* Flere retter samme dag står i den rækkefølge, køkkenet vil
     have dem — ikke i den, de blev skrevet. */
  sortering    int not null default 0,

  oprettet     timestamptz not null default now(),
  aendret      timestamptz not null default now(),

  constraint dagens_ret_navn_ok
    check (char_length(btrim(navn)) between 1 and 120),
  constraint dagens_ret_tekst_ok
    check (beskrivelse is null or char_length(beskrivelse) <= 600),
  constraint dagens_ret_pris_ok
    check (pris is null or (pris >= 0 and pris < 10000)),
  constraint dagens_ret_antal_ok
    check (antal_tilbage is null or antal_tilbage between 0 and 999)
);

comment on table public.dagens_retter is
  'Dagens retter pr. dato. Erstatter indstillingen dagens_ret, som kun kunne rumme én ret på én dag.';
comment on column public.dagens_retter.antal_tilbage is
  'Portioner tilbage. Tælles NED af mosede_dagens_ret_bremse() ved hver bestilling. Tomt = der tælles ikke.';

create index if not exists dagens_retter_dag_idx
  on public.dagens_retter (lokation_id, dato, sortering, id);

/* ⚠️ TO RÆKKER MED SAMME NAVN PÅ SAMME DAG ER EN TASTEFEJL, ikke
   to retter: gæsten ville se den samme ret to gange med hver sin
   pris, og køkkenet kunne ikke se, hvilken der gjaldt.

   OG DEN SKAL SAMMENLIGNE SOM TÆLLEREN GØR. Første udgave var en
   almindelig unique (lokation_id, dato, navn) — men bremsen
   nedenfor matcher på lower(btrim(navn)), og så kunne "Stegt
   flæsk" og "stegt flæsk " ligge side om side og BEGGE blive
   talt ned af den samme bestilling. Prøve 5 fandt det. Et
   udtryksindeks kan det, en tabel-constraint ikke kan. */
create unique index if not exists dagens_ret_ikke_dobbelt
  on public.dagens_retter (lokation_id, dato, lower(btrim(navn)));

-- ------------------------------------------------------------
-- 2) ADGANGEN
--    ---------------------------------------------------------
--    Alle må LÆSE: det er dagens ret, den står på forsiden.
--    Der er ikke ét menneskes navn eller nummer i tabellen.
--    Kun personalet må skrive.
-- ------------------------------------------------------------
alter table public.dagens_retter enable row level security;

drop policy if exists dagens_retter_laes_alle on public.dagens_retter;
create policy dagens_retter_laes_alle on public.dagens_retter
  for select using (true);

drop policy if exists dagens_retter_opret_admin on public.dagens_retter;
create policy dagens_retter_opret_admin on public.dagens_retter
  for insert to authenticated
  with check (public.is_admin_for(lokation_id));

drop policy if exists dagens_retter_ret_admin on public.dagens_retter;
create policy dagens_retter_ret_admin on public.dagens_retter
  for update to authenticated
  using (public.is_admin_for(lokation_id))
  with check (public.is_admin_for(lokation_id));

drop policy if exists dagens_retter_slet_admin on public.dagens_retter;
create policy dagens_retter_slet_admin on public.dagens_retter
  for delete to authenticated
  using (public.is_admin_for(lokation_id));

-- ------------------------------------------------------------
-- 3) TÆLLINGEN
--    ---------------------------------------------------------
--    En bestilling kommer ind med sine linjer som jsonb:
--      [{ "navn": "Stegt flæsk", "antal": 2, "pris": 89 }, …]
--
--    Bremsen løber linjerne igennem, finder de retter, der står
--    på bestillingens dag, og trækker fra. Rammer et antal nul,
--    sættes udsolgt af sig selv.
--
--    DEN SIGER IKKE NEJ, og det er et valg. Køkkenet må gerne
--    kunne sige ja til nummer elleve, når de kan se, at der er
--    dej tilbage — men SIDEN skal holde op med at love den.
--    Formularen viser ikke en udsolgt ret (se Butik.dagensRetter),
--    så en bestilling, der når hertil på en udsolgt ret, er
--    personalets egen, taget i telefonen.
--
--    security definer: gæsten må ikke rette i tabellen selv, og
--    bremsen skal kunne. search_path låst, som alle de andre.
-- ------------------------------------------------------------
create or replace function public.mosede_dagens_ret_bremse()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  linje jsonb;
  stk   int;
begin
  if new.linjer is null then return new; end if;

  for linje in select * from jsonb_array_elements(new.linjer)
  loop
    stk := coalesce((linje ->> 'antal')::int, 0);
    if stk <= 0 then continue; end if;

    /* greatest(...) og ikke bare minus: to gæster, der trykker i
       samme sekund, må ikke kunne trække antallet under nul og
       gøre en udsolgt ret bestilbar igen med et negativt tal.
       Rækken låses af UPDATE'et, så den anden venter på den
       første. */
    update public.dagens_retter r
       set antal_tilbage = greatest(r.antal_tilbage - stk, 0),
           udsolgt = (greatest(r.antal_tilbage - stk, 0) = 0),
           aendret = now()
     where r.lokation_id = new.lokation_id
       and r.dato = new.hent_dato
       and r.antal_tilbage is not null
       and lower(btrim(r.navn)) = lower(btrim(coalesce(linje ->> 'navn', '')));
  end loop;

  return new;
end $$;

comment on function public.mosede_dagens_ret_bremse() is
  'Tæller dagens retter ned efter bestillingens linjer og sætter udsolgt ved nul.';

drop trigger if exists bestilling_taeller_dagens_ret on public.bestillinger;
create trigger bestilling_taeller_dagens_ret
  after insert on public.bestillinger
  for each row execute function public.mosede_dagens_ret_bremse();

commit;

-- ------------------------------------------------------------
--  ER DEN LANDET?
--  Supabases SQL Editor viser kun den SIDSTE sætnings svar.
-- ------------------------------------------------------------
select
  (select count(*) from information_schema.tables
    where table_schema = 'public' and table_name = 'dagens_retter')
    as "tabellen (skal være 1)",
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'dagens_retter')
    as "adgangsregler (skal være 4)",
  (select count(*) from pg_trigger
    where tgname = 'bestilling_taeller_dagens_ret')
    as "taelleren (skal være 1)",
  (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'mosede_dagens_ret_bremse'
      and p.prosecdef)
    as "taelleren er security definer (skal være 1)";
