-- ============================================================
--  FORESPØRGSLER: CATERING, BAGLOKALE OG SELSKAB  (fase 2)
--  ------------------------------------------------------------
--  Kør EFTER flerlejer.sql. Filen bruger is_admin_for() fra den
--  migration og laver derfor sine adgangsregler pr. forretning
--  med det samme — der er ingen gammel udgave at migrere fra.
--
--  Rækkefølgen er altså:
--    setup.sql → flerlejer.sql → bremse.sql → menukort.sql
--    → forespoergsler.sql → proev-flerlejer.sql
--
--  Kan køres igen uden at ødelægge noget.
--
--  ------------------------------------------------------------
--  HVORFOR ÉN TABEL OG IKKE TRE
--  ------------------------------------------------------------
--  De tre indgange spørger om hver sit — mad ud af huset, et
--  lokale, en fest — men personalet gør det samme ved dem alle:
--  ringer, aftaler eller afviser. Tre tabeller ville være tre sæt
--  adgangsregler at holde ens, tre faner at rette, og tre steder
--  at huske, den dag der skal et felt mere på. Forskellen er ét
--  ord i en kolonne, ikke tre systemer.
--
--  Og adgangsreglerne er den vigtige del: en forespørgsel er navn
--  og telefonnummer på et menneske, der har fortalt, hvornår de
--  holder fest — altså også hvornår de ikke er hjemme. Tre steder
--  at holde den regel rigtig er tre steder at få den forkert.
--
--  ------------------------------------------------------------
--  KØRER DU DEN PÅ EN BAR POSTGRES?
--  ------------------------------------------------------------
--  Supabase giver selv anon og authenticated adgang til nye
--  tabeller. Gør du det ikke, kan gæsten ikke sende noget. Kør:
--
--    grant all on all tables in schema public to anon, authenticated;
--    grant usage, select on all sequences in schema public
--      to anon, authenticated;
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1) TABELLEN
-- ------------------------------------------------------------
/* id er en IDENTITY-kolonne og ikke bigserial.

   Det er den samme fælde som ved bestillingerne, og den er værd
   at skrive ned igen: med bigserial ejes sekvensen af skemaet, og
   gæsten (rollen anon) mangler usage på den. Resultatet er
   "permission denied for sequence …" — en fejl, der ligner et
   hul i adgangsreglerne, men ikke er det. Med identity ejer
   kolonnen sin sekvens, og der er ikke en rettighed at glemme. */
create table if not exists public.forespoergsler (
  id            bigint generated by default as identity primary key,

  -- Koden gæsten får at vide. Laves i browseren, fordi gæsten
  -- ikke må kunne læse tabellen bagefter. FO, hvor bestillinger
  -- har SM: personalet har de to lister ved siden af hinanden.
  reference     text not null unique,

  lokation_id   text not null default 'mosede' references public.lokationer(id) on delete cascade,

  -- Hvilken af de tre indgange gæsten kom ind ad. Listen står
  -- også i js/store.js som FORESPOERGSEL_TYPER. Kommer der en
  -- fjerde til, skal begge rettes — proev-forespoergsler.sql
  -- fanger, hvis kun det ene bliver gjort.
  type          text not null,

  navn          text not null,
  telefon       text not null,
  email         text,

  /* Dato og antal er FRIVILLIGE, og det er ikke sjusk.
     "Vi skal holde sølvbryllup engang til foråret, hvad koster
     det?" er en helt rigtig forespørgsel, og et krav om en dato
     ville sende netop den gæst væk igen. Personalet ser "ikke
     oplyst" på kortet og spørger i telefonen. */
  dato          date,
  antal_personer int,

  besked        text,

  status        text not null default 'ny',
  -- Personalets egen note. En gæst må ikke kunne skrive i den:
  -- adgangsreglen nedenfor kræver, at den er tom ved oprettelse.
  intern_note   text,

  oprettet      timestamptz not null default now(),
  aendret       timestamptz not null default now(),

  /* Lag 3 af valideringen. Formularen tjekker det samme, og
     js/store.js tjekker det igen — men en formular kan omgås med
     to linjer i konsollen, og databasen kan ikke. */
  constraint forespoergsel_type_ok
    check (type in ('catering', 'baglokale', 'selskab')),

  constraint forespoergsel_navn_ok
    check (char_length(btrim(navn)) between 2 and 80),

  constraint forespoergsel_telefon_ok
    check (char_length(regexp_replace(telefon, '[^0-9]', '', 'g')) between 8 and 15),

  constraint forespoergsel_email_ok
    check (email is null or email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[a-zA-Z]{2,}$'),

  /* To år frem, hvor bestillinger kun har 120 dage. Et bryllup
     bliver planlagt halvandet år i forvejen, og en grænse, der
     passer til smørrebrød i overmorgen, ville afvise præcis den
     forespørgsel, der er mest værd. Det ene døgn bagud dækker, at
     Danmark er en time foran UTC. */
  constraint forespoergsel_dato_ok
    check (dato is null or dato between current_date - 1 and current_date + 730),

  constraint forespoergsel_antal_ok
    check (antal_personer is null or antal_personer between 1 and 500),

  constraint forespoergsel_besked_ok
    check (besked is null or char_length(besked) <= 1000),

  constraint forespoergsel_status_ok
    check (status in ('ny', 'kontaktet', 'aftalt', 'afvist'))
);

comment on table public.forespoergsler is
  'Catering, baglokale og selskaber. Gæsten må skrive, kun personalet må læse.';

-- Personalet åbner fanen og vil se de nye først.
create index if not exists forespoergsler_status_idx
  on public.forespoergsler (status, oprettet desc);

-- Én pr. tælling i bremsen nedenfor. Uden dem skal Postgres læse
-- hele tabellen igennem for hver eneste forespørgsel.
create index if not exists forespoergsler_bremse_nummer_idx
  on public.forespoergsler (telefon, oprettet desc);

create index if not exists forespoergsler_bremse_sted_idx
  on public.forespoergsler (lokation_id, oprettet desc);


-- ------------------------------------------------------------
-- 2) ADGANGEN: GÆSTEN MÅ SKRIVE, MEN IKKE LÆSE
--    ------------------------------------------------------------
--    Præcis samme regel som ved bestillingerne, og af præcis
--    samme grund. Anon-nøglen ligger offentligt i js/config.js —
--    den er lavet til det. Måtte den læse her, kunne enhver hente
--    navn, telefonnummer og festdato på hver eneste kunde med én
--    linje i en browserkonsol.
--
--    Det er ikke en teoretisk risiko. Det er en liste over folk,
--    der holder sølvbryllup på lørdag og altså ikke er hjemme.
--
--    HVAD GÆSTEN IKKE MÅ SÆTTE: status skal være 'ny', og den
--    interne note skal være tom. Uden det kunne man indsætte en
--    forespørgsel, der ser aftalt ud, eller skrive i personalets
--    eget felt.
--
--    Tre separate regler i stedet for én "for all": en for-all
--    ville også gælde læsning, og så skulle hver eneste gæst køre
--    is_admin_for() bare for at se menukortet.
-- ------------------------------------------------------------
alter table public.forespoergsler enable row level security;

drop policy if exists forespoergsler_opret_gaest on public.forespoergsler;
create policy forespoergsler_opret_gaest on public.forespoergsler
  for insert to anon, authenticated
  with check (status = 'ny' and intern_note is null);

drop policy if exists forespoergsler_laes_admin on public.forespoergsler;
create policy forespoergsler_laes_admin on public.forespoergsler
  for select using (public.is_admin_for(lokation_id));

drop policy if exists forespoergsler_ret_admin on public.forespoergsler;
create policy forespoergsler_ret_admin on public.forespoergsler
  for update using (public.is_admin_for(lokation_id))
  with check (public.is_admin_for(lokation_id));

drop policy if exists forespoergsler_slet_admin on public.forespoergsler;
create policy forespoergsler_slet_admin on public.forespoergsler
  for delete using (public.is_admin_for(lokation_id));


-- ------------------------------------------------------------
-- 3) BREMSEN
--    ------------------------------------------------------------
--    Som supabase/bremse.sql, og bygget af samme grund: hvad en
--    browser kan gøre én gang, kan et script gøre ti tusind
--    gange. Tallene er lavere end bestillingernes, fordi en
--    forespørgsel er sjældnere — man spørger om ét selskab, ikke
--    om frokost hver torsdag.
--
--    security definer er HELE forudsætningen. Gæsten er anon og
--    må ikke læse tabellen, så uden det ville begge tællinger
--    give nul, og bremsen ville se ud til at virke uden at gøre
--    noget overhovedet.
--
--    Fejlnavnene står i teksten med vilje: js/store.js kender dem
--    og oversætter dem til noget, en gæst kan bruge. Retter du et
--    navn her, skal det rettes dér.
-- ------------------------------------------------------------
create or replace function public.forespoergsel_bremse()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  lige_nu      int;
  fra_nummeret int;
  paa_stedet   int;
begin
  /* Dobbelttryk først. Bestillingerne har en unik nøgle på
     (telefon, dag, tid), men den kan ikke bruges her: dato er
     frivillig, og to NULL'er støder ikke sammen i en unik nøgle.
     Så en gæst uden dato kunne trykke ti gange, og databasen
     ville tage imod alle ti.

     Derfor et tidsvindue i stedet — og "is not distinct from",
     ikke "=", netop fordi datoen kan være NULL. Ti minutter
     rammer dobbelttrykket og den utålmodige, men spærrer ikke
     for at spørge igen næste år. */
  select count(*) into lige_nu
    from public.forespoergsler f
   where f.telefon = new.telefon
     and f.type = new.type
     and f.dato is not distinct from new.dato
     and f.oprettet > now() - interval '10 minutes';

  if lige_nu >= 1 then
    raise exception 'forespoergsel_dobbelt';
  end if;

  select count(*) into fra_nummeret
    from public.forespoergsler f
   where f.telefon = new.telefon
     and f.oprettet > now() - interval '24 hours';

  if fra_nummeret >= 3 then
    raise exception 'forespoergsel_bremse_nummer';
  end if;

  select count(*) into paa_stedet
    from public.forespoergsler f
   where f.lokation_id = new.lokation_id
     and f.oprettet > now() - interval '1 hour';

  if paa_stedet >= 20 then
    raise exception 'forespoergsel_bremse_travlt';
  end if;

  return new;
end $$;

/* Kun ved insert. Personalet skal kunne rette status hele dagen
   uden at støde ind i en bremse, der er bygget mod noget helt
   andet. */
drop trigger if exists forespoergsel_bremse on public.forespoergsler;
create trigger forespoergsel_bremse
  before insert on public.forespoergsler
  for each row execute function public.forespoergsel_bremse();

commit;

-- ------------------------------------------------------------
--  ER DEN LANDET?
--  ------------------------------------------------------------
--  Linjen står her, fordi Supabases SQL Editor kun viser den
--  SIDSTE sætnings svar — notices og warnings ser man aldrig.
--  Står der ikke fire regler og én udløser, er noget gået galt.
-- ------------------------------------------------------------
select
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'forespoergsler') as "adgangsregler (skal være 4)",
  (select count(*) from pg_trigger
    where tgrelid = 'public.forespoergsler'::regclass and not tgisinternal) as "bremser (skal være 1)",
  (select count(*) from public.forespoergsler) as "forespørgsler i tabellen";

-- ------------------------------------------------------------
--  BAGEFTER
--  ------------------------------------------------------------
--  Kør supabase/proev-forespoergsler.sql. Den prøver at læse på
--  tværs af to forretninger og ruller sig selv tilbage. Består
--  den ikke, kan én kunde se en andens gæster.
-- ------------------------------------------------------------
