-- ============================================================
--  KALENDEREN  (fase 3)
--  ------------------------------------------------------------
--  Kør EFTER flerlejer.sql. Kan køres igen uden at ødelægge noget.
--
--  Rækkefølgen er:
--    setup.sql → flerlejer.sql → bremse.sql → menukort.sql
--    → forespoergsler.sql → kalender.sql → prøverne
--
--  ------------------------------------------------------------
--  ÉN TABEL TIL TRE TING, OG HVORFOR
--  ------------------------------------------------------------
--  Et arrangement, en lukkedag og en tidlig lukning er tre
--  forskellige beskeder til gæsten, men det er det SAMME
--  spørgsmål: hvad sker der den dag?
--
--  Og det er dét spørgsmål, alt det, der kommer bagefter, skal
--  stille. Bordbestilling skal vide, om der er lukket. Udlejning
--  af baglokalet skal vide, om lokalet allerede er optaget. To
--  steder at holde styr på, hvad der sker hvornår, er præcis
--  dér, dobbeltbookinger opstår — derfor kommer kalenderen FØR
--  dem begge.
--
--  ------------------------------------------------------------
--  DEN ERSTATTER lukkedage
--  ------------------------------------------------------------
--  Rækkerne flyttes med herunder. Den gamle tabel bliver stående
--  og bliver bare ikke læst mere: så kan man se, hvad der stod,
--  hvis noget ser forkert ud bagefter. Den slettes i en senere
--  oprydning, når den nye har kørt et stykke tid.
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1) TABELLEN
-- ------------------------------------------------------------
/* identity og ikke bigserial — samme fælde som ved
   bestillingerne: med bigserial ejes sekvensen af skemaet, og en
   gæst mangler usage på den. Her skriver gæsten ganske vist
   ingenting, men tabellen skal kunne LÆSES af anon, og den næste,
   der kopierer mønsteret herfra, skal ikke arve fejlen. */
create table if not exists public.kalender (
  id          bigint generated by default as identity primary key,
  lokation_id text not null default 'mosede' references public.lokationer(id) on delete cascade,

  type        text not null,

  dato        date not null,
  /* Tom slutdato = én dag. En vinterlukning er én række med en
     slutdato, ikke halvfems rækker — ellers skal personalet
     klikke halvfems gange og huske at slette halvfems igen. */
  slut_dato   date,

  titel       text not null,
  beskrivelse text,
  emoji       text,

  -- Kun ved tidlig lukning: hvornår lukkes der så i stedet
  lukker_kl   time,

  /* Arrangementer vises kun for gæsterne, hvis det her er sat.
     Personalet skriver også ting i kalenderen, som kun de skal
     se — "Bent har ferie", "leverandøren kommer" — og de må ikke
     havne på hjemmesiden, fordi nogen glemte at tænke over det.
     Derfor er standarden FALSE: man skal aktivt vælge at vise
     noget offentligt. */
  offentlig   boolean not null default false,

  oprettet    timestamptz not null default now(),
  aendret     timestamptz not null default now(),

  constraint kalender_type_ok
    check (type in ('arrangement', 'lukkedag', 'tidlig_lukning')),

  constraint kalender_titel_ok
    check (char_length(btrim(titel)) between 1 and 120),

  constraint kalender_beskrivelse_ok
    check (beskrivelse is null or char_length(beskrivelse) <= 2000),

  constraint kalender_emoji_ok
    check (emoji is null or char_length(emoji) <= 8),

  constraint kalender_slutdato_ok
    check (slut_dato is null or slut_dato >= dato),

  /* En tidlig lukning UDEN et klokkeslæt er ingenting: den siger
     "vi lukker tidligt" uden at sige hvornår, og så står gæsten
     ved en lukket luge. */
  constraint kalender_lukker_kl_ok
    check ((type = 'tidlig_lukning') = (lukker_kl is not null))
);

comment on table public.kalender is
  'Arrangementer, lukkedage og tidlige lukninger. Erstatter lukkedage.';

-- Forsiden spørger "hvad sker der i dag og de næste dage"
create index if not exists kalender_dato_idx
  on public.kalender (lokation_id, dato);


-- ------------------------------------------------------------
-- 2) DE GAMLE LUKKEDAGE FLYTTER MED
--    ------------------------------------------------------------
--    Kun dem, der ikke allerede er flyttet: filen skal kunne
--    køres igen uden at lave dubletter. Titlen bliver årsagen —
--    stod der ingen, bliver den "Lukket", for titlen er not null
--    og en tom overskrift på en kalender siger ingenting.
-- ------------------------------------------------------------
/* Flytningen ligger i en FUNKTION og ikke løst i filen, så
   supabase/proev-kalender.sql kan kalde præcis den samme kode.

   Første udgave havde flytningen som en løs sætning her, og
   prøven tjekkede bagefter "har hver gammel lukkedag fået en
   række?". Den bestod — men databasen havde nul gamle lukkedage,
   så den spurgte til en tom mængde og kunne ikke fejle. En prøve,
   der ikke kan fejle, måler ingenting; og migrationen er den
   farligste del af hele filen. Går den galt, forsvinder
   forretningens juleaften fra forsiden, og ingen opdager det før
   den 24. december. */
create or replace function public.kalender_flyt_lukkedage() returns int
language plpgsql as $$
declare flyttet int;
begin
  insert into public.kalender (lokation_id, type, dato, titel, emoji, offentlig)
  select l.lokation_id, 'lukkedag', l.dato,
         coalesce(nullif(btrim(l.aarsag), ''), 'Lukket'), l.emoji, true
    from public.lukkedage l
   where not exists (
     select 1 from public.kalender k
      where k.lokation_id = l.lokation_id
        and k.dato = l.dato
        and k.type = 'lukkedag');

  get diagnostics flyttet = row_count;
  return flyttet;
end $$;

-- Kun personalet skal kunne køre en migration.
revoke all on function public.kalender_flyt_lukkedage() from public;

select public.kalender_flyt_lukkedage();


-- ------------------------------------------------------------
-- 3) ADGANGEN
--    ------------------------------------------------------------
--    Her er reglen en ANDEN end ved bestillinger og
--    forespørgsler, og forskellen er værd at forstå.
--
--    De to andre må gæsten SKRIVE i og ikke læse. Kalenderen er
--    omvendt: gæsten må LÆSE dele af den og ikke skrive noget.
--    Forsiden skal kunne sige "Lukket i dag · Juleaften" uden at
--    nogen er logget ind.
--
--    Men kun DELE af den. Lukkedage og tidlige lukninger er
--    offentlige i sig selv — de afgør, om der er åbent, og det
--    står på forsiden alligevel. Arrangementer skal aktivt sættes
--    til offentlige, for personalet skriver også deres eget i
--    kalenderen.
-- ------------------------------------------------------------
alter table public.kalender enable row level security;

drop policy if exists kalender_laes_alle on public.kalender;
create policy kalender_laes_alle on public.kalender
  for select
  using (type in ('lukkedag', 'tidlig_lukning') or offentlig);

drop policy if exists kalender_laes_admin on public.kalender;
create policy kalender_laes_admin on public.kalender
  for select using (public.is_admin_for(lokation_id));

drop policy if exists kalender_opret_admin on public.kalender;
create policy kalender_opret_admin on public.kalender
  for insert with check (public.is_admin_for(lokation_id));

drop policy if exists kalender_ret_admin on public.kalender;
create policy kalender_ret_admin on public.kalender
  for update using (public.is_admin_for(lokation_id))
  with check (public.is_admin_for(lokation_id));

drop policy if exists kalender_slet_admin on public.kalender;
create policy kalender_slet_admin on public.kalender
  for delete using (public.is_admin_for(lokation_id));

commit;

-- ------------------------------------------------------------
--  ER DEN LANDET?
--  Supabases SQL Editor viser kun den SIDSTE sætnings svar.
-- ------------------------------------------------------------
select
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'kalender') as "adgangsregler (skal være 5)",
  (select count(*) from public.kalender where type = 'lukkedag') as "lukkedage flyttet med",
  (select count(*) from public.lukkedage) as "i den gamle tabel";

-- ------------------------------------------------------------
--  BAGEFTER
--  ------------------------------------------------------------
--  Kør supabase/proev-kalender.sql. Den vigtigste prøve dér er,
--  at en gæst KAN se en lukkedag og IKKE et internt arrangement:
--  begge dele står i samme tabel, og forskellen er én kolonne.
-- ------------------------------------------------------------
