-- ============================================================
--  LOGBOGEN: HVEM ÆNDREDE HVAD, OG HVORNÅR
--  ------------------------------------------------------------
--  Kør EFTER skraldespand.sql. Kan køres igen uden at ødelægge
--  noget.
--
--  HVORFOR
--  ------------------------------------------------------------
--  Der er flere om skærmen. Én står ved lugen, én sidder med
--  iPaden, chefen kigger hjemmefra. Når en bestilling pludselig
--  står som afvist, er spørgsmålet ikke "hvad står der" — det er
--  "hvem gjorde det, og hvornår". Det svar har systemet ikke
--  kunnet give.
--
--  HVAD DER *IKKE* LOGGES, OG HVORFOR
--  ------------------------------------------------------------
--  Oprettelser. En ny bestilling er sit eget bevis: rækken ligger
--  der, med navn, telefon og tidspunkt. En logbogslinje oveni
--  ville være den samme oplysning gemt to gange — altså dobbelt
--  så mange steder, hvor en gæsts telefonnummer ligger.
--
--  Af samme grund gemmes hverken bestillingens linjer eller
--  gæstens egen besked. Logbogen skal svare på "hvem rørte den",
--  ikke være en skyggekopi af tabellen ved siden af.
--
--  HVAD DER SÅ LOGGES
--  ------------------------------------------------------------
--  Rettelser og sletninger på de fire gæstetabeller: hvem, hvad,
--  hvornår, og HVILKE FELTER der blev anderledes — kun dem.
--
--  EN LOGBOG, MAN KAN RETTE I, ER IKKE EN LOGBOG
--  ------------------------------------------------------------
--  Derfor er der ingen update-regel overhovedet. Hverken personale
--  eller gæst kan skrive i en linje, der er skrevet. Det eneste,
--  der kan ske med den, er, at den bliver for gammel: linjer
--  ældre end 180 dage ryddes, når personalet logger ind.
--
--  ------------------------------------------------------------
--  KØRER DU DEN PÅ EN BAR POSTGRES?
--  ------------------------------------------------------------
--  Supabase giver selv anon og authenticated adgang til nye
--  tabeller. Gør du det ikke, kan personalet ikke læse logbogen.
--  Kør:
--
--    grant all on all tables in schema public to anon, authenticated;
--    grant usage, select on all sequences in schema public
--      to anon, authenticated;
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1) TABELLEN
--    id er IDENTITY og ikke bigserial — samme fælde som ved de
--    andre tabeller: med bigserial ejer skemaet sekvensen, og
--    rollen mangler usage på den.
-- ------------------------------------------------------------
create table if not exists public.logbog (
  id          bigint generated by default as identity primary key,

  lokation_id text not null default 'mosede'
              references public.lokationer(id) on delete cascade,

  -- Hvilken tabel og hvilken række. raekke_id er IKKE en
  -- fremmednøgle: rækken kan være slettet for altid, og det er
  -- netop dét, linjen fortæller om.
  tabel       text not null,
  raekke_id   bigint,

  -- Nok til at læse linjen uden at slå noget op. Referencen er
  -- den, personalet kender fra listerne.
  reference   text,
  navn        text,

  hvad        text not null,
  -- E-mailen på den, der var logget ind. NULL betyder, at det
  -- ikke var et menneske med et login — i praksis sker det ikke,
  -- for gæsten kan kun oprette, og oprettelser logges ikke.
  hvem        text,

  -- Kun de felter, der faktisk blev anderledes. Se trigger'en
  -- nedenfor: aendret springes over, for den ændrer sig hver gang
  -- og fortæller ingenting.
  foer        jsonb,
  efter       jsonb,

  hvornaar    timestamptz not null default now(),

  constraint logbog_hvad_ok
    check (hvad in ('rettet', 'i skraldespanden', 'hentet tilbage',
                    'slettet for altid')),

  constraint logbog_tabel_ok
    check (tabel in ('bestillinger', 'forespoergsler',
                     'bordbestillinger', 'udlejninger'))
);

comment on table public.logbog is
  'Hvem ændrede hvad hvornår. Kun rettelser og sletninger — oprettelser er deres egen række.';

-- Personalet åbner fanen og vil se det nyeste først.
create index if not exists logbog_tid_idx
  on public.logbog (lokation_id, hvornaar desc);

-- "Hvad er der sket med DEN her bestilling?"
create index if not exists logbog_raekke_idx
  on public.logbog (tabel, raekke_id, hvornaar desc);


-- ------------------------------------------------------------
-- 2) ADGANGEN
--    ------------------------------------------------------------
--    Læs: kun personale, og kun for egen forretning. Linjerne
--    indeholder navne og referencer på gæster — samme slags
--    oplysning som tabellerne selv, og samme regel.
--
--    Skriv: INGEN. Ikke engang personalet. Linjerne kommer fra
--    trigger'en nedenfor, som kører security definer og derfor er
--    ligeglad med reglerne her. En logbog, personalet kan skrive
--    i, svarer ikke længere på det spørgsmål, den findes for.
--
--    Slet: personale. Ikke for at kunne rydde spor væk, men fordi
--    linjer skal kunne blive for gamle — se punkt 4.
-- ------------------------------------------------------------
alter table public.logbog enable row level security;

drop policy if exists logbog_laes_admin on public.logbog;
create policy logbog_laes_admin on public.logbog
  for select using (public.is_admin_for(lokation_id));

drop policy if exists logbog_slet_admin on public.logbog;
create policy logbog_slet_admin on public.logbog
  for delete using (public.is_admin_for(lokation_id));


-- ------------------------------------------------------------
-- 3) SKRIVEREN
--    ------------------------------------------------------------
--    Én funktion til alle fire tabeller. TG_TABLE_NAME fortæller,
--    hvor den blev kaldt fra, så der ikke skal holdes fire
--    næsten ens funktioner ens.
--
--    security definer er forudsætningen: der er ingen
--    insert-regel på logbog, og der skal ikke være en. Uden
--    definer ville hver eneste statusknap i admin fejle.
--
--    search_path = '' og fuldt udskrevne navne hører med: en
--    definer-funktion med løs søgesti er den klassiske vej til at
--    køre fremmed kode som ejeren.
-- ------------------------------------------------------------
create or replace function public.logbog_skriv()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  gl      jsonb;
  ny      jsonb;
  hvad_   text;
  foer_   jsonb := '{}'::jsonb;
  efter_  jsonb := '{}'::jsonb;
  n       text;
  raekke  record;
begin
  if TG_OP = 'DELETE' then
    raekke := old;
    hvad_  := 'slettet for altid';
  else
    raekke := new;
    gl := to_jsonb(old);
    ny := to_jsonb(new);

    /* Hvad SKETE der? Skraldespanden er ikke "en rettelse" — det
       er den handling, personalet leder efter, når noget er væk,
       og den skal kunne ses uden at læse to jsonb-klumper. */
    if old.slettet is null and new.slettet is not null then
      hvad_ := 'i skraldespanden';
    elsif old.slettet is not null and new.slettet is null then
      hvad_ := 'hentet tilbage';
    else
      hvad_ := 'rettet';
    end if;

    /* Kun det, der blev anderledes.
       - aendret springes over: den ændrer sig HVER gang og
         fortæller ingenting
       - linjer og besked springes over: det er gæstens egne ord
         og hele bestillingen, og logbogen skal ikke være en
         skyggekopi af tabellen ved siden af */
    for n in select jsonb_object_keys(ny)
    loop
      continue when n in ('aendret', 'linjer', 'besked');
      if gl -> n is distinct from ny -> n then
        foer_  := foer_  || jsonb_build_object(n, gl -> n);
        efter_ := efter_ || jsonb_build_object(n, ny -> n);
      end if;
    end loop;

    -- Rørte nogen ved rækken uden at ændre noget, er der ikke
    -- sket noget at skrive om.
    if efter_ = '{}'::jsonb then
      return new;
    end if;
  end if;

  insert into public.logbog
    (lokation_id, tabel, raekke_id, reference, navn, hvad, hvem, foer, efter)
  values (
    raekke.lokation_id, TG_TABLE_NAME, raekke.id, raekke.reference, raekke.navn,
    hvad_,
    nullif(coalesce(auth.jwt() ->> 'email', ''), ''),
    case when TG_OP = 'DELETE' then null else foer_ end,
    case when TG_OP = 'DELETE' then null else efter_ end
  );

  if TG_OP = 'DELETE' then return old; end if;
  return new;
end $$;

/* AFTER og ikke BEFORE. En logbogslinje om noget, der bagefter
   bliver rullet tilbage af en anden regel, ville være en linje om
   noget, der ikke skete. */
do $$
declare t text;
begin
  foreach t in array array['bestillinger', 'forespoergsler',
                           'bordbestillinger', 'udlejninger']
  loop
    execute format('drop trigger if exists logbog on public.%I', t);
    execute format(
      'create trigger logbog after update or delete on public.%I '
      'for each row execute function public.logbog_skriv()', t);
  end loop;
end $$;

commit;

-- ------------------------------------------------------------
--  ER DEN LANDET?
--  Supabases SQL Editor viser kun den SIDSTE sætnings svar.
-- ------------------------------------------------------------
select
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'logbog')
    as "adgangsregler (skal være 2)",
  (select count(*) from pg_trigger
    where tgname = 'logbog' and not tgisinternal)
    as "skrivere (skal være 4)",
  (select count(*) from public.logbog) as "linjer i logbogen";

-- ------------------------------------------------------------
--  BAGEFTER
--  Kør supabase/proev-logbog.sql. Den prøver blandt andet at
--  skrive i logbogen som chef — og skal få nej.
-- ------------------------------------------------------------
