-- ============================================================
--  PUSH: TELEFONERNE, DER SKAL HAVE BESKED  (fase 5c)
--  ------------------------------------------------------------
--  Kør EFTER flerlejer.sql — filen bruger is_admin_for() derfra.
--  Rækkefølgen er altså:
--    setup.sql → flerlejer.sql → bremse.sql → menukort.sql
--    → forespoergsler.sql → kalender.sql → borde.sql
--    → udlejning.sql → push.sql
--
--  Kan køres igen uden at ødelægge noget.
--
--  ------------------------------------------------------------
--  HVAD TABELLEN ER
--  ------------------------------------------------------------
--  Én række pr. telefon/iPad, der har sagt ja til at få besked,
--  når der kommer noget ind. endpoint + p256dh + auth er Web
--  Push-abonnementet, som browseren selv udleverer — adressen er
--  hemmelig i praksis (den er selve retten til at sende til
--  enheden), så tabellen er lukket land for gæster.
--
--  Edge Function'en send-push læser tabellen med service_role og
--  er derfor ligeglad med reglerne her. Reglerne findes for alle
--  andre: KUN personale for forretningen må se og røre dens
--  enheder. En gæst med anon-nøglen må hverken tilmelde en
--  telefon (spam til køkkenet) eller læse listen (adresserne).
-- ============================================================

begin;

create table if not exists public.push_abonnementer (
  id            bigint generated by default as identity primary key,

  lokation_id   text not null default 'mosede' references public.lokationer(id) on delete cascade,

  -- Hvem slog den til, og på hvad. Ikke til adgangskontrol — kun
  -- så listen i admin kan læses af et menneske: "Mikkels iPhone".
  email         text not null,
  enhed         text,

  endpoint      text not null unique,
  p256dh        text not null,
  auth          text not null,

  oprettet      timestamptz not null default now(),

  constraint push_email_ok
    check (char_length(btrim(email)) between 3 and 160),

  constraint push_enhed_ok
    check (enhed is null or char_length(enhed) <= 120),

  constraint push_endpoint_ok
    check (endpoint like 'https://%' and char_length(endpoint) <= 1000),

  constraint push_noegler_ok
    check (char_length(p256dh) between 20 and 300
       and char_length(auth) between 10 and 100)
);

comment on table public.push_abonnementer is
  'Telefoner der får push ved nye bestillinger m.m. Kun personale må læse og skrive; send-push læser med service_role.';

-- ------------------------------------------------------------
--  ADGANGEN: KUN PERSONALE, OG KUN FOR EGEN FORRETNING
--  Ingen gæsteregel overhovedet — det er hele pointen. anon har
--  RLS slået til og ingen regler, så svaret er nej til alt.
-- ------------------------------------------------------------
alter table public.push_abonnementer enable row level security;

drop policy if exists push_laes_admin on public.push_abonnementer;
create policy push_laes_admin on public.push_abonnementer
  for select using (public.is_admin_for(lokation_id));

drop policy if exists push_opret_admin on public.push_abonnementer;
create policy push_opret_admin on public.push_abonnementer
  for insert with check (public.is_admin_for(lokation_id));

drop policy if exists push_ret_admin on public.push_abonnementer;
create policy push_ret_admin on public.push_abonnementer
  for update using (public.is_admin_for(lokation_id))
  with check (public.is_admin_for(lokation_id));

drop policy if exists push_slet_admin on public.push_abonnementer;
create policy push_slet_admin on public.push_abonnementer
  for delete using (public.is_admin_for(lokation_id));

commit;

-- ------------------------------------------------------------
--  ER DEN LANDET?
--  Supabases SQL Editor viser kun den SIDSTE sætnings svar.
-- ------------------------------------------------------------
select
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'push_abonnementer') as "adgangsregler (skal være 4)",
  (select count(*) from public.push_abonnementer) as "tilmeldte enheder";

-- ------------------------------------------------------------
--  BAGEFTER
--  Kør supabase/proev-push.sql — den beviser, at en gæst hverken
--  kan tilmelde en telefon eller læse listen, og ruller sig selv
--  tilbage.
-- ------------------------------------------------------------
