-- ============================================================
--  UDLEJNING AF BAGLOKALET  (fase 5)
--  ------------------------------------------------------------
--  Kør EFTER flerlejer.sql — filen bruger is_admin_for() derfra.
--  Rækkefølgen er altså:
--    setup.sql → flerlejer.sql → bremse.sql → menukort.sql
--    → forespoergsler.sql → kalender.sql → borde.sql
--    → udlejning.sql
--
--  Kan køres igen uden at ødelægge noget.
--
--  ------------------------------------------------------------
--  SOM BORDENE — MEN ÉT JA OPTAGER HELE DAGEN
--  ------------------------------------------------------------
--  En række er et ØNSKE om at leje lokalet, og ja'et gives i
--  admin som ved bordene. Forskellen er reglen, der er hele
--  grunden til, at fasen findes: lokalet er ET lokale. To
--  bekræftede udlejninger på samme dag er to selskaber i samme
--  rum, og den fejl må ikke kunne begås — heller ikke af to
--  medarbejdere, der siger ja samtidig fra hver sin iPad.
--
--  Derfor håndhæves ja'et af databasen selv: et delvist unikt
--  indeks tillader kun ÉN bekræftet udlejning pr. dag pr.
--  forretning. Ønsker og afviste rører det ikke — ti kan spørge
--  om den samme lørdag, men kun én kan få ja. Ved bordene er
--  kapaciteten med vilje blød (pladser er personalets redskab og
--  ændrer sig); lokalet er hårdt, for "ét lokale" ændrer sig ikke.
--
--  ------------------------------------------------------------
--  KØRER DU DEN PÅ EN BAR POSTGRES?
--  ------------------------------------------------------------
--  Supabase giver selv anon og authenticated adgang til nye
--  tabeller. Gør du det ikke, kan gæsten ikke sende noget. Kør:
--
--    grant all on all tables in schema public to anon, authenticated;
--    grant usage, select on all sequences in schema public
--      to anon, authenticated;
-- ============================================================

begin;

-- ------------------------------------------------------------
-- 1) TABELLEN
-- ------------------------------------------------------------
/* id er en IDENTITY-kolonne og ikke bigserial — samme fælde som
   ved bestillingerne: med bigserial mangler anon usage på
   sekvensen, og fejlen ligner et hul i adgangsreglerne uden at
   være det. */
create table if not exists public.udlejninger (
  id            bigint generated by default as identity primary key,

  -- Koden gæsten får at vide. BL, hvor bestillinger har SM,
  -- forespørgsler FO og bordene BO.
  reference     text not null unique,

  lokation_id   text not null default 'mosede' references public.lokationer(id) on delete cascade,

  navn          text not null,
  telefon       text not null,
  email         text,

  /* Datoen er PÅKRÆVET — lokalet lejes pr. dag, og "engang" kan
     personalet ikke sige ja til. Er datoen ikke fastlagt endnu,
     er det en FORESPØRGSEL, og den indgang findes allerede på
     selskabssiden. Klokkeslættet er derimod en del af samtalen:
     dagen er alligevel optaget, så det aftales i telefonen. */
  dato          date not null,
  antal_personer int,

  besked        text,

  status        text not null default 'ny',
  -- Personalets egen note. Adgangsreglen kræver, at den er tom
  -- ved oprettelse — gæsten må ikke skrive i personalets felt.
  intern_note   text,

  oprettet      timestamptz not null default now(),
  aendret       timestamptz not null default now(),

  /* Lag 3 af valideringen — formularen og js/store.js tjekker det
     samme, men en formular kan omgås med to linjer i konsollen. */
  constraint udlejning_navn_ok
    check (char_length(btrim(navn)) between 2 and 80),

  constraint udlejning_telefon_ok
    check (char_length(regexp_replace(telefon, '[^0-9]', '', 'g')) between 8 and 15),

  constraint udlejning_email_ok
    check (email is null or email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[a-zA-Z]{2,}$'),

  /* To år frem som forespørgslerne — en konfirmation planlægges
     halvandet år i forvejen, og grænsen, der passer til et bord i
     overmorgen, ville afvise præcis det ønske, der er mest værd.
     Det ene døgn bagud dækker, at Danmark er en time foran UTC. */
  constraint udlejning_dato_ok
    check (dato between current_date - 1 and current_date + 730),

  constraint udlejning_antal_ok
    check (antal_personer is null or antal_personer between 1 and 500),

  constraint udlejning_besked_ok
    check (besked is null or char_length(besked) <= 1000),

  constraint udlejning_status_ok
    check (status in ('ny', 'bekraeftet', 'afvist')),

  -- Dobbelttryk: samme telefon, samme dag er ét ønske — ikke to.
  constraint udlejning_ikke_dobbelt
    unique (telefon, dato)
);

comment on table public.udlejninger is
  'Ønsker om at leje baglokalet. Gæsten må skrive, kun personalet må læse — og kun ÉN pr. dag kan få ja.';

/* HELE FASENS POINTE PÅ ÉN LINJE: der kan kun findes én BEKRÆFTET
   udlejning pr. dag pr. forretning. Et delvist unikt indeks og
   ikke en regel i admin-koden: to medarbejdere på hver sin iPad
   kan trykke ja samtidig, og så er JavaScript for sent på den.
   Navnet står i fejlen, og js/store.js oversætter det. */
create unique index if not exists udlejning_dagen_er_taget
  on public.udlejninger (lokation_id, dato)
  where (status = 'bekraeftet');

-- Personalet åbner fanen og vil se de nye først — og lokalets
-- kalender samles pr. dato.
create index if not exists udlejninger_status_idx
  on public.udlejninger (status, oprettet desc);

create index if not exists udlejninger_dato_idx
  on public.udlejninger (lokation_id, dato);

-- Én pr. tælling i bremsen nedenfor.
create index if not exists udlejninger_bremse_nummer_idx
  on public.udlejninger (telefon, oprettet desc);

create index if not exists udlejninger_bremse_sted_idx
  on public.udlejninger (lokation_id, oprettet desc);


-- ------------------------------------------------------------
-- 2) ADGANGEN: GÆSTEN MÅ SKRIVE, MEN IKKE LÆSE
--    Samme regel som de tre andre tabeller, af samme grund: en
--    række er navn og telefonnummer på et menneske, der har
--    fortalt, hvornår de holder fest — altså hvornår de ikke er
--    hjemme. Og gæsten må ikke kunne sætte status eller skrive i
--    personalets note.
-- ------------------------------------------------------------
alter table public.udlejninger enable row level security;

drop policy if exists udlejninger_opret_gaest on public.udlejninger;
create policy udlejninger_opret_gaest on public.udlejninger
  for insert to anon, authenticated
  with check (status = 'ny' and intern_note is null);

drop policy if exists udlejninger_laes_admin on public.udlejninger;
create policy udlejninger_laes_admin on public.udlejninger
  for select using (public.is_admin_for(lokation_id));

drop policy if exists udlejninger_ret_admin on public.udlejninger;
create policy udlejninger_ret_admin on public.udlejninger
  for update using (public.is_admin_for(lokation_id))
  with check (public.is_admin_for(lokation_id));

drop policy if exists udlejninger_slet_admin on public.udlejninger;
create policy udlejninger_slet_admin on public.udlejninger
  for delete using (public.is_admin_for(lokation_id));


-- ------------------------------------------------------------
-- 3) BREMSEN
--    Lavere tal end bordene: man lejer ét lokale til én fest,
--    ikke frokost hver torsdag. Dobbelttrykket fanges af den
--    unikke nøgle (telefon, dato) — datoen er påkrævet her, så
--    nøglen virker uden et tidsvindue.
--
--    security definer er HELE forudsætningen: gæsten er anon og
--    må ikke læse tabellen, så uden det ville tællingerne give
--    nul, og bremsen ville se ud til at virke uden at gøre noget.
-- ------------------------------------------------------------
create or replace function public.udlejning_bremse()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  fra_nummeret int;
  paa_stedet   int;
begin
  select count(*) into fra_nummeret
    from public.udlejninger u
   where u.telefon = new.telefon
     and u.oprettet > now() - interval '24 hours';

  if fra_nummeret >= 2 then
    raise exception 'udlejning_bremse_nummer';
  end if;

  select count(*) into paa_stedet
    from public.udlejninger u
   where u.lokation_id = new.lokation_id
     and u.oprettet > now() - interval '1 hour';

  if paa_stedet >= 10 then
    raise exception 'udlejning_bremse_travlt';
  end if;

  return new;
end $$;

/* Kun ved insert. Personalet skal kunne bekræfte og afvise hele
   dagen uden at støde ind i en bremse mod noget helt andet. */
drop trigger if exists udlejning_bremse on public.udlejninger;
create trigger udlejning_bremse
  before insert on public.udlejninger
  for each row execute function public.udlejning_bremse();

commit;

-- ------------------------------------------------------------
--  ER DEN LANDET?
--  Supabases SQL Editor viser kun den SIDSTE sætnings svar. Står
--  der ikke fire regler, én bremse og ét dagen-er-taget-indeks,
--  er noget gået galt.
-- ------------------------------------------------------------
select
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'udlejninger') as "adgangsregler (skal være 4)",
  (select count(*) from pg_trigger
    where tgrelid = 'public.udlejninger'::regclass and not tgisinternal) as "bremser (skal være 1)",
  (select count(*) from pg_indexes
    where schemaname = 'public' and indexname = 'udlejning_dagen_er_taget') as "dagen-er-taget (skal være 1)",
  (select count(*) from public.udlejninger) as "udlejningsønsker i tabellen";

-- ------------------------------------------------------------
--  BAGEFTER
--  Kør supabase/proev-udlejning.sql. Den beviser, at to ønsker om
--  samme dag kan FINDES, men at kun ét kan få ja — og ruller sig
--  selv tilbage.
-- ------------------------------------------------------------
