-- ============================================================
--  ⚠️⚠️  DEN HER FIL MÅ ALDRIG KØRES I SUPABASE  ⚠️⚠️
--  ------------------------------------------------------------
--  Den er en EFTERLIGNING af produktionens tabeller til en lokal
--  Postgres, så proev-*.sql kan køres, før de sendes til ejeren.
--  Den hører ikke hjemme i supabase/-mappen, og der er en spærre
--  nederst i det her hoved, der stopper den i et Supabase-projekt.
--
--  BRUG:
--    createdb mosede_proev
--    psql -q -d mosede_proev -f vaerktoej/lokal-stub.sql
--    psql -q -d mosede_proev -f supabase/DEN-FIL-DU-SKRIVER.sql
--    psql -q -d mosede_proev -f supabase/proev-DEN-FIL.sql
--
--  ------------------------------------------------------------
--  ⚠️ HVORFOR FILEN FINDES — TRE FALD, SAMME MØNSTER
--  ------------------------------------------------------------
--  Hver gang en prøvefil er blevet efterprøvet mod en stub, der
--  er bygget forfra i hånden, har stubben været MILDERE end
--  skyen — og filen har bestået lokalt og fejlet hos kunden:
--
--    26/8  `dagens_retter` fandtes ikke i produktionen; nødmenuen
--          stod på hjemmesiden med to varer
--    30/8  `lokationer.adresse` er `not null` i setup.sql; en
--          stub med tre kolonner tog imod, skyen sagde 23502
--     1/9  `mosede_bord_findes` (bordkort.sql) afviser en
--          bestilling til et bord, der ikke findes. Stubben havde
--          hverken tabellen `borde` eller værnet, så
--          proev-bord-uden-telefon.sql bestod 8 af 8 lokalt og
--          faldt med 4 af 8 i Mosede-projektet
--
--  ⚠️ SKRIVER DIN PRØVE I EN TABEL, SÅ SE FØRST EFTER, HVILKE
--  UDLØSERE DER STÅR PÅ DEN I HELE supabase/-MAPPEN:
--
--    grep -rn "on public.DIN_TABEL" supabase/*.sql | grep trigger
--
--  Står der en udløser, stubben ikke har, beviser prøven
--  ingenting om lige den regel.
-- ============================================================

-- ⚠️ SPÆRREN. Supabase har altid auth.users; en lokal Postgres
--    har den ikke. Uden den her kunne et forkert vindue koste en
--    kundes database.
do $$
begin
  if exists (select 1 from information_schema.tables
              where table_schema = 'auth' and table_name = 'users') then
    raise exception
      'STOP: vaerktoej/lokal-stub.sql er en LOKAL efterligning og må '
      'aldrig køres i Supabase. Kør supabase/-filerne i stedet.';
  end if;
end $$;

-- Fra og med her: en tom, lokal database forventes. Filen laver
-- IKKE "drop schema public cascade" med vilje — opret en frisk
-- database i stedet, så en tastefejl ikke kan koste noget.

create table if not exists public.lokationer (
  id text primary key, navn text not null,
  -- ⚠️ De tre er `not null` i setup.sql (linje 101). En stub uden
  --    dem tager imod det, produktionen afviser (arret fra 30/8).
  adresse text not null, postnr text not null, by text not null,
  telefon text, email text, sortering int not null default 0,
  aktiv boolean not null default true, beskrivelse text,
  oprettet timestamptz not null default now()
);
insert into public.lokationer (id, navn, adresse, postnr, by)
values ('mosede', 'Mosede Havnecafe', 'Havnevej 20I', '2670', 'Greve')
on conflict (id) do nothing;

create table if not exists public.indstillinger (
  lokation_id text not null default 'mosede' references public.lokationer(id),
  noegle text not null, vaerdi jsonb not null,
  aendret timestamptz not null default now(),
  -- ⚠️ Primærnøglen er (lokation_id, noegle) — flerlejer.sql
  --    linje 231 gjorde den til det. IKKE `noegle` alene.
  primary key (lokation_id, noegle)
);

create table if not exists public.borde (
  id bigint generated by default as identity primary key,
  lokation_id text not null default 'mosede' references public.lokationer(id),
  nummer text not null, pladser int, placering text, zone text,
  aktiv boolean not null default true, sortering int not null default 0,
  oprettet timestamptz not null default now()
);

create table if not exists public.dags_regler (
  id bigserial primary key,
  lokation_id text not null default 'mosede' references public.lokationer(id),
  dato date not null,
  luk_takeaway boolean not null default false,
  luk_spis_her boolean not null default false,
  tidligst time, senest_togo time, senest_spis_her time,
  besked_til_gaester text, besked_titel text,
  aendret timestamptz not null default now()
);
create index if not exists dags_regler_dato_idx
  on public.dags_regler (lokation_id, dato);

create table if not exists public.bestillinger (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  lokation_id text not null default 'mosede' references public.lokationer(id),
  navn text not null, telefon text not null, email text,
  hent_dato date not null, hent_tid time not null,
  linjer jsonb not null, fyld jsonb not null default '[]'::jsonb,
  antal int not null, besked text, allergi text,
  status text not null default 'ny', intern_note text, slettet timestamptz,
  hvordan text not null default 'afhentning',
  leverings_adresse text, bord_nummer text, nummer integer,
  oprettet timestamptz not null default now(),
  aendret timestamptz not null default now(),
  constraint bestilling_navn_ok check (char_length(btrim(navn)) between 2 and 80),
  constraint bestilling_telefon_ok
    check (char_length(regexp_replace(telefon, '[^0-9]', '', 'g')) between 8 and 15),
  constraint bestilling_dato_ok
    check (hent_dato between current_date - 1 and current_date + 120),
  constraint bestilling_antal_ok check (antal between 1 and 500),
  constraint bestilling_linjer_ok
    check (jsonb_typeof(linjer) = 'array' and jsonb_array_length(linjer) between 1 and 60),
  constraint bestilling_hvordan_ok check (hvordan in ('afhentning','spis_her','levering')),
  constraint bestilling_bord_nummer_ok
    check (bord_nummer is null or char_length(btrim(bord_nummer)) between 1 and 40),
  constraint bestilling_bord_spis_her_ok
    check (bord_nummer is null or hvordan = 'spis_her')
);
-- Dubletvagten er et DELVIST indeks (restaurant.sql): bordene er
-- holdt ude, fordi de aldrig vælger en hentetid.
create unique index if not exists bestilling_ikke_dobbelt
  on public.bestillinger (telefon, hent_dato, hent_tid)
  where slettet is null and bord_nummer is null;

/* ⚠️ VÆRNET FRA bordkort.sql: BORDET SKAL FINDES.
   Det var DEN her, der manglede 1/9. Skriver din prøve en
   bestilling med et bord_nummer, skal bordet oprettes først. */
create or replace function public.mosede_bord_findes()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.bord_nummer is null then return new; end if;
  if not exists (
    select 1 from public.borde b
     where b.lokation_id = new.lokation_id and b.aktiv
       and lower(btrim(b.nummer)) = lower(btrim(new.bord_nummer))
  ) then
    raise exception 'bestilling_ukendt_bord';
  end if;
  return new;
end $$;
drop trigger if exists bestilling_bord_findes on public.bestillinger;
create trigger bestilling_bord_findes before insert on public.bestillinger
  for each row execute function public.mosede_bord_findes();

create table if not exists public.bordbestillinger (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  lokation_id text not null default 'mosede' references public.lokationer(id),
  navn text not null, telefon text not null, email text,
  dato date not null, tid time not null, antal_personer int not null,
  besked text, status text not null default 'ny',
  intern_note text, slettet timestamptz,
  oprettet timestamptz not null default now(),
  aendret timestamptz not null default now(),
  constraint bord_status_ok
    check (status in ('ny','bekraeftet','afvist','udeblevet'))
);

/* ⚠️ BREMSEN FRA borde.sql: 3 pr. nummer i døgnet, 20 pr.
   forretning i timen. En prøve, der booker mange gange i træk,
   rammer den 20. — og gør det KUN i produktionen, hvis stubben
   ikke har den med. */
create or replace function public.bord_bremse()
returns trigger language plpgsql security definer
set search_path = public, pg_temp as $$
declare fra_nummeret int; paa_stedet int;
begin
  select count(*) into fra_nummeret from public.bordbestillinger b
   where b.telefon = new.telefon and b.oprettet > now() - interval '24 hours';
  if fra_nummeret >= 3 then raise exception 'bord_bremse_nummer'; end if;
  select count(*) into paa_stedet from public.bordbestillinger b
   where b.lokation_id = new.lokation_id
     and b.oprettet > now() - interval '1 hour';
  if paa_stedet >= 20 then raise exception 'bord_bremse_travlt'; end if;
  return new;
end $$;
drop trigger if exists bord_bremse on public.bordbestillinger;
create trigger bord_bremse before insert on public.bordbestillinger
  for each row execute function public.bord_bremse();

select 'Stubben står. Kør nu din supabase/-fil og derefter dens proev-fil.'
  as "klar";
